server:
  port: 8080

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui

spring:

  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
#    baseline-on-migrate: true
#    baseline-version: 1
    locations: classpath:db/migration

#app:
#  email:
#    support: support@provider.com
#    confirmation:
#      url: http://localhost:8080/api/users/confirm-email
