server:
  port: 8080

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui

spring:

  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  support:
    email: support@providermanagementsystem.com
#    confirmation:
#      url: http://localhost:8080/api/users/confirm-email
